<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>IBPAD</font>
## <font color='blue'>Projeto Final Trainee CRM</font>
## <font color='blue'>Raul Maximiliano de Carvalho Fidelis</font>

## Instalando e Carregando os Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.

O procedimento de instalação dos pacotes está no arquivo LEIAME.txt

In [2]:
# https://pypi.org/project/squarify/
%pip install -q squarify

Note: you may need to restart the kernel to use updated packages.

In [3]:
# Imports
import sklearn
import squarify
import pandas as pd
import seaborn as sns
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from datetime import datetime, timedelta

## Carregando e Explorando os Dados

In [4]:
# Carrega o dataset
df_rmx = pd.read_csv("essenza_crm.csv", sep=";")

In [5]:
# Shape
df_rmx.shape

(5000, 24)

In [6]:
# Amostra de dados
df_rmx.head()

,cliente_id,data_disparo,dia_semana,canal,tipo_campanha,segmento_cliente,genero,faixa_etaria,opt_in_email,opt_in_sms,...,numero_disparos_30d,dias_desde_ultima_compra,frequencia_compras_historica,ticket_medio_historico_brl,abriu,clicou,converteu,valor_compra_brl,categoria_produto,dias_ate_recompra
0,CLI00360,2024-03-05,Terça,SMS,Carrinho Abandonado,Inativo,Não informado,35-44,Sim,Sim,...,4,292,4,99.06,Sim,Não,Não,0.0,NaN,NaN
1,CLI01161,2024-08-07,Quarta,Push,Programa de Fidelidade,VIP,F,35-44,Sim,Não,...,10,56,12,616.48,Não,Não,Não,0.0,NaN,NaN
2,CLI01749,2024-03-18,Segunda,SMS,Carrinho Abandonado,Ativo,F,18-24,Não,Sim,...,5,45,14,171.31,Sim,Sim,Não,0.0,NaN,NaN
3,CLI01010,2024-08-12,Segunda,E-mail,Aniversário,Ativo,M,45-54,Sim,Sim,...,3,17,15,266.37,Sim,Sim,Não,0.0,NaN,NaN
4,CLI01588,2025-05-25,Domingo,SMS,Conteúdo/Educativo,Ativo,F,25-34,Sim,Sim,...,2,72,15,243.77,Não,Não,Não,0.0,NaN,NaN

In [7]:
df_rmx.opt_in_email.value_counts()

opt_in_email
Sim    4548
Não     452
Name: count, dtype: int64

In [8]:
df_rmx.opt_in_email.replace('Sim', 1, inplace = True)
df_rmx.opt_in_email.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2800890923.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_email.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2800890923.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_email.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2800890923.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.opt_in_email.replace('Não', 0, inplace = True)

In [9]:
df_rmx.opt_in_sms.value_counts()

opt_in_sms
Sim    3254
Não    1746
Name: count, dtype: int64

In [10]:
df_rmx.opt_in_sms.replace('Sim', 1, inplace = True)
df_rmx.opt_in_sms.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\344477126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_sms.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\344477126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_sms.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\344477126.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.opt_in_sms.replace('Não', 0, inplace = True)

In [11]:
df_rmx.opt_in_push.value_counts()

opt_in_push
Sim    3044
Não    1956
Name: count, dtype: int64

In [12]:
df_rmx.opt_in_push.replace('Sim', 1, inplace = True)
df_rmx.opt_in_push.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1195815490.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_push.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1195815490.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_push.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1195815490.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.opt_in_push.replace('Não', 0, inplace = True)

In [13]:
df_rmx.teve_desconto.value_counts()

teve_desconto
Não    3517
Sim    1483
Name: count, dtype: int64

In [14]:
df_rmx.teve_desconto.replace('Sim', 1, inplace = True)
df_rmx.teve_desconto.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1816953267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.teve_desconto.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1816953267.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.teve_desconto.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\1816953267.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.teve_desconto.replace('Não', 0, inplace = True)

In [15]:
df_rmx.opt_in_whatsapp.value_counts()

opt_in_whatsapp
Sim    3599
Não    1401
Name: count, dtype: int64

In [16]:
df_rmx.opt_in_whatsapp.replace('Sim', 1, inplace = True)
df_rmx.opt_in_whatsapp.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\3542478519.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_whatsapp.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\3542478519.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.opt_in_whatsapp.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\3542478519.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.opt_in_whatsapp.replace('Não', 0, inplace = True)

In [17]:
df_rmx.abriu.value_counts()

abriu
Não    3009
Sim    1991
Name: count, dtype: int64

In [18]:
df_rmx.abriu.replace('Sim', 1, inplace = True)
df_rmx.abriu.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\320118595.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.abriu.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\320118595.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.abriu.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\320118595.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.abriu.replace('Não', 0, inplace = True)

In [19]:
df_rmx.clicou.value_counts()

clicou
Não    4231
Sim     769
Name: count, dtype: int64

In [20]:
df_rmx.clicou.replace('Sim', 1, inplace = True)
df_rmx.clicou.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2021910910.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.clicou.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2021910910.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.clicou.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\2021910910.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.clicou.replace('Não', 0, inplace = True)

In [21]:
df_rmx.converteu.value_counts()

converteu
Não    4682
Sim     318
Name: count, dtype: int64

In [22]:
df_rmx.converteu.replace('Sim', 1, inplace = True)
df_rmx.converteu.replace('Não', 0, inplace = True)

C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\4021161556.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.converteu.replace('Sim', 1, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\4021161556.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rmx.converteu.replace('Não', 0, inplace = True)
C:\Users\Raul\AppData\Local\Temp\ipykernel_47436\4021161556.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_rmx.converteu.replace('Não', 0, inplace = True)

In [23]:
df_rmx['data_disparo'] = pd.to_datetime(df_rmx['data_disparo'], format='%Y-%m-%d')

In [24]:
df_rmx['categoria_produto'] = df_rmx['categoria_produto'].fillna('Não Informado')

In [25]:
df_rmx['dias_ate_recompra'] = df_rmx['dias_ate_recompra'].fillna(0)

In [26]:
df_rmx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cliente_id                    5000 non-null   object
 1   data_disparo                  5000 non-null   datetime64[ns]
 2   dia_semana                    5000 non-null   object
 3   canal                         5000 non-null   object
 4   tipo_campanha                 5000 non-null   object
 5   segmento_cliente              5000 non-null   object
 6   genero                        5000 non-null   object
 7   faixa_etaria                  5000 non-null   object
 8   opt_in_email                  5000 non-null   int64
 9   opt_in_sms                    5000 non-null   int64
 10  opt_in_push                   5000 non-null   int64
 11  opt_in_whatsapp               5000 non-null   int64
 12  teve_desconto                 5000 non-null   int64
 13  pct_desconto                  5000 non-null   int64
 14  numero_disparos_30d           5000 non-null   int64
 15  dias_desde_ultima_compra      5000 non-null   int64
 16  frequencia_compras_historica  5000 non-null   int64
 17  ticket_medio_historico_brl    5000 non-null   float64
 18  abriu                         5000 non-null   int64
 19  clicou                        5000 non-null   int64
 20  converteu                     5000 non-null   int64
 21  valor_compra_brl              5000 non-null   float64
 22  categoria_produto             5000 non-null   object
 23  dias_ate_recompra             5000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(12), object(8)
memory usage: 937.6+ KB

In [27]:
df_rmx.head()

,cliente_id,data_disparo,dia_semana,canal,tipo_campanha,segmento_cliente,genero,faixa_etaria,opt_in_email,opt_in_sms,...,numero_disparos_30d,dias_desde_ultima_compra,frequencia_compras_historica,ticket_medio_historico_brl,abriu,clicou,converteu,valor_compra_brl,categoria_produto,dias_ate_recompra
0,CLI00360,2024-03-05,Terça,SMS,Carrinho Abandonado,Inativo,Não informado,35-44,1,1,...,4,292,4,99.06,1,0,0,0.0,Não Informado,0.0
1,CLI01161,2024-08-07,Quarta,Push,Programa de Fidelidade,VIP,F,35-44,1,0,...,10,56,12,616.48,0,0,0,0.0,Não Informado,0.0
2,CLI01749,2024-03-18,Segunda,SMS,Carrinho Abandonado,Ativo,F,18-24,0,1,...,5,45,14,171.31,1,1,0,0.0,Não Informado,0.0
3,CLI01010,2024-08-12,Segunda,E-mail,Aniversário,Ativo,M,45-54,1,1,...,3,17,15,266.37,1,1,0,0.0,Não Informado,0.0
4,CLI01588,2025-05-25,Domingo,SMS,Conteúdo/Educativo,Ativo,F,25-34,1,1,...,2,72,15,243.77,0,0,0,0.0,Não Informado,0.0

In [28]:
# 1. Tudo minúsculo
df_rmx['dia_semana'] = df_rmx['dia_semana'].str.lower()

# 2. Remove espaços em branco no início ou no fim
df_rmx['dia_semana'] = df_rmx['dia_semana'].str.strip()

# 3. Remove a palavra "-feira"
df_rmx['dia_semana'] = df_rmx['dia_semana'].str.replace('-feira', '', regex=False)

# 4. Tira acentos e cedilha (terça -> terca, sábado -> sabado)
df_rmx['dia_semana'] = df_rmx['dia_semana'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [29]:
# Criamos o "dicionário tradutor"
mapa_dias = {
    'segunda': 0,
    'terca': 1,
    'quarta': 2,
    'quinta': 3,
    'sexta': 4,
    'sabado': 5,
    'domingo': 6
}

# Criamos uma nova coluna numérica baseada na coluna de texto
df_rmx['dia_semana_num'] = df_rmx['dia_semana'].map(mapa_dias)

In [30]:
# Cria uma coluna que recebe 1 se for Sábado(5) ou Domingo(6), e 0 se for dia útil
df_rmx['is_fim_de_semana'] = df_rmx['dia_semana_num'].apply(lambda x: 1 if x >= 5 else 0)

In [31]:
df_rmx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cliente_id                    5000 non-null   object
 1   data_disparo                  5000 non-null   datetime64[ns]
 2   dia_semana                    5000 non-null   object
 3   canal                         5000 non-null   object
 4   tipo_campanha                 5000 non-null   object
 5   segmento_cliente              5000 non-null   object
 6   genero                        5000 non-null   object
 7   faixa_etaria                  5000 non-null   object
 8   opt_in_email                  5000 non-null   int64
 9   opt_in_sms                    5000 non-null   int64
 10  opt_in_push                   5000 non-null   int64
 11  opt_in_whatsapp               5000 non-null   int64
 12  teve_desconto                 5000 non-null   int64
 13  pct_desconto                  5000 non-null   int64
 14  numero_disparos_30d           5000 non-null   int64
 15  dias_desde_ultima_compra      5000 non-null   int64
 16  frequencia_compras_historica  5000 non-null   int64
 17  ticket_medio_historico_brl    5000 non-null   float64
 18  abriu                         5000 non-null   int64
 19  clicou                        5000 non-null   int64
 20  converteu                     5000 non-null   int64
 21  valor_compra_brl              5000 non-null   float64
 22  categoria_produto             5000 non-null   object
 23  dias_ate_recompra             5000 non-null   float64
 24  dia_semana_num                5000 non-null   int64
 25  is_fim_de_semana              5000 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(14), object(8)
memory usage: 1015.8+ KB

In [32]:
df_rmx = df_rmx.drop(columns=['dia_semana'])

In [33]:
df_rmx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cliente_id                    5000 non-null   object
 1   data_disparo                  5000 non-null   datetime64[ns]
 2   canal                         5000 non-null   object
 3   tipo_campanha                 5000 non-null   object
 4   segmento_cliente              5000 non-null   object
 5   genero                        5000 non-null   object
 6   faixa_etaria                  5000 non-null   object
 7   opt_in_email                  5000 non-null   int64
 8   opt_in_sms                    5000 non-null   int64
 9   opt_in_push                   5000 non-null   int64
 10  opt_in_whatsapp               5000 non-null   int64
 11  teve_desconto                 5000 non-null   int64
 12  pct_desconto                  5000 non-null   int64
 13  numero_disparos_30d           5000 non-null   int64
 14  dias_desde_ultima_compra      5000 non-null   int64
 15  frequencia_compras_historica  5000 non-null   int64
 16  ticket_medio_historico_brl    5000 non-null   float64
 17  abriu                         5000 non-null   int64
 18  clicou                        5000 non-null   int64
 19  converteu                     5000 non-null   int64
 20  valor_compra_brl              5000 non-null   float64
 21  categoria_produto             5000 non-null   object
 22  dias_ate_recompra             5000 non-null   float64
 23  dia_semana_num                5000 non-null   int64
 24  is_fim_de_semana              5000 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(14), object(7)
memory usage: 976.7+ KB

In [34]:
df_rmx.faixa_etaria.value_counts()

faixa_etaria
25-34    1608
35-44    1362
18-24     923
45-54     692
55+       415
Name: count, dtype: int64

In [35]:
# Dicionário com a ordem lógica das idades
mapa_idade = {
    '18-24': 0,
    '25-34': 1,
    '35-44': 2,
    '45-54': 3,
    '55+': 4
}

# Nova coluna numérica
df_rmx['faixa_etaria_num'] = df_rmx['faixa_etaria'].map(mapa_idade)

# Dropei a coluna de texto antiga para limpar a base
df_rmx.drop(columns=['faixa_etaria'], inplace=True)

In [36]:
df_rmx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cliente_id                    5000 non-null   object
 1   data_disparo                  5000 non-null   datetime64[ns]
 2   canal                         5000 non-null   object
 3   tipo_campanha                 5000 non-null   object
 4   segmento_cliente              5000 non-null   object
 5   genero                        5000 non-null   object
 6   opt_in_email                  5000 non-null   int64
 7   opt_in_sms                    5000 non-null   int64
 8   opt_in_push                   5000 non-null   int64
 9   opt_in_whatsapp               5000 non-null   int64
 10  teve_desconto                 5000 non-null   int64
 11  pct_desconto                  5000 non-null   int64
 12  numero_disparos_30d           5000 non-null   int64
 13  dias_desde_ultima_compra      5000 non-null   int64
 14  frequencia_compras_historica  5000 non-null   int64
 15  ticket_medio_historico_brl    5000 non-null   float64
 16  abriu                         5000 non-null   int64
 17  clicou                        5000 non-null   int64
 18  converteu                     5000 non-null   int64
 19  valor_compra_brl              5000 non-null   float64
 20  categoria_produto             5000 non-null   object
 21  dias_ate_recompra             5000 non-null   float64
 22  dia_semana_num                5000 non-null   int64
 23  is_fim_de_semana              5000 non-null   int64
 24  faixa_etaria_num              5000 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(15), object(6)
memory usage: 976.7+ KB

In [37]:
df_rmx.head()

,cliente_id,data_disparo,canal,tipo_campanha,segmento_cliente,genero,opt_in_email,opt_in_sms,opt_in_push,opt_in_whatsapp,...,ticket_medio_historico_brl,abriu,clicou,converteu,valor_compra_brl,categoria_produto,dias_ate_recompra,dia_semana_num,is_fim_de_semana,faixa_etaria_num
0,CLI00360,2024-03-05,SMS,Carrinho Abandonado,Inativo,Não informado,1,1,1,1,...,99.06,1,0,0,0.0,Não Informado,0.0,1,0,2
1,CLI01161,2024-08-07,Push,Programa de Fidelidade,VIP,F,1,0,1,0,...,616.48,0,0,0,0.0,Não Informado,0.0,2,0,2
2,CLI01749,2024-03-18,SMS,Carrinho Abandonado,Ativo,F,0,1,1,0,...,171.31,1,1,0,0.0,Não Informado,0.0,0,0,0
3,CLI01010,2024-08-12,E-mail,Aniversário,Ativo,M,1,1,1,1,...,266.37,1,1,0,0.0,Não Informado,0.0,0,0,3
4,CLI01588,2025-05-25,SMS,Conteúdo/Educativo,Ativo,F,1,1,0,1,...,243.77,0,0,0,0.0,Não Informado,0.0,6,1,1

In [38]:
df_rmx.describe()

,data_disparo,opt_in_email,opt_in_sms,opt_in_push,opt_in_whatsapp,teve_desconto,pct_desconto,numero_disparos_30d,dias_desde_ultima_compra,frequencia_compras_historica,ticket_medio_historico_brl,abriu,clicou,converteu,valor_compra_brl,dias_ate_recompra,dia_semana_num,is_fim_de_semana,faixa_etaria_num
count,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2024-09-29 19:17:11.040000256,0.909600,0.650800,0.608800,0.719800,0.296600,4.827000,4.815800,112.53000,7.725800,204.996054,0.398200,0.153800,0.063600,15.343394,8.401600,2.974600,0.278200,1.613600
min,2024-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.00000,1.000000,70.850000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024-05-16 00:00:00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,29.00000,3.000000,133.752500,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
50%,2024-09-30 00:00:00,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,66.00000,5.000000,168.600000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000
75%,2025-02-14 00:00:00,1.000000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,144.00000,12.000000,227.430000,1.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1.000000,2.000000
max,2025-06-30 00:00:00,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,15.000000,540.00000,24.000000,699.850000,1.000000,1.000000,1.000000,916.870000,365.000000,6.000000,1.000000,4.000000
std,NaN,0.286783,0.476765,0.488068,0.449142,0.456804,8.373715,2.828475,123.23088,6.655785,124.304212,0.489576,0.360793,0.244063,70.932425,39.005315,1.985735,0.448157,1.175318